### ISSUE TITLE
Forcing Data to return as JSON instead of Base64 Encode

### ISSUE THREAD

**Issue by sedkis** [Difrex/zoorest#2]
Would be nice to force the data to be returned as JSON, seeing as the payload returned by the v1/get/ endpoint returns JSON anyhow.

when I do `localhost:9998/zoorest/v1/get/zk_tyk` I want the field in "data" to be JSON

**Comment by Difrex** [comment]
Hi,
The main problem with the forced JSON data is you can add any binary data to the node.

See:
```
curl -XPUT localhost:8889/v1/up/this/a/binary --data-binary @/usr/bin/ls 
/this/a/binary
curl -s localhost:8889/v1/get/this/a/binary | jq -r .data | base64 -d > ls_from_zk && md5sum ls_from_zk /usr/bin/ls
0e1631f5eaadf5ac5010530077727092  ls_from_zk
0e1631f5eaadf5ac5010530077727092  /usr/bin/ls
```

But, it's will be simple to add a method something like `/v1/get/path/to/node?json-data`.
